### ISSUE TITLE
.entries() does not return keys

### ISSUE THREAD

**Issue by mayask** [ActiveObject/immutable-map#1]
Hi

`.entries()` does not return keys, but values. See example:

```js
var m = Map.Empty;
m = m.set('first', 1);
m = m.set('second', 2);
m = m.set('third', 3);
m.entries();      // [ [ 3, undefined ], [ 1, undefined ], [ 2, undefined ] ]
```

**Comment by vpryim-old** [comment]
@myaskevich nice to see see you here! 

This project is a part of my research on immutable data structures. All the ground work was done in https://github.com/ActiveObject/immutable-trie. If you are interested in immutable data structures I highly recommend https://facebook.github.io/immutable-js/. It's a mature project that you can use for production.

**Comment by mayask** [comment]
Hi @ActiveObject 

Thanks!

I was looking for Immutable OrderedMap implementation as a separate package and stumbled upon your project.

I didn't want to pull the entire monster-size immutable-js package just to use Maps.
Also it's quite cool to see how the internals work, because immutable-js is huge and it's easy to get lost in details.

Keep up the good work and thanks again for the fix!

**Comment by myaskevich** [comment]
Hi @ActiveObject 

Thanks!

I was looking for Immutable OrderedMap implementation as a separate package and stumbled upon your project.

I didn't want to pull the entire monster-size immutable-js package just to use Maps.
Also it's quite cool to see how the internals work, because immutable-js is huge and it's easy to get lost in details.

Keep up the good work and thanks again for the fix!
